version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    assignees:
      - "danividanivi"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "enhancement"
    ignore:
      # Ignore major version updates for now
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore specific packages that might need manual testing
      - dependency-name: "puppeteer"
        update-types: ["version-update:semver-major"]
