name: Build Resume

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cv-resume:latest .

      - name: Generate artifacts (Docker)
        run: |
          docker run --name cv-build cv-resume:latest
          docker cp cv-build:/app/index.html index.html
          docker cp cv-build:/app/resume.pdf resume.pdf
          docker cp cv-build:/app/resume.txt resume.txt
          docker cp cv-build:/app/resume.pdf.sha256 resume.pdf.sha256
          docker rm cv-build
          ls -l index.html resume.pdf resume.txt resume.pdf.sha256
          echo "Checksum:" && cat resume.pdf.sha256

      - name: Upload resume artifacts (for non-main branches)
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: resume-artifacts
          path: |
            resume.pdf
            resume.txt
            index.html
            resume.pdf.sha256

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4