name: Build Resume

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install resume-cli
      run: npm install resume-cli

    - name: Install dependencies
      run: |
        npm install puppeteer
        npm install ./danivi-style
        echo "Verifying puppeteer installation..."
        npx puppeteer --version
        echo "Configuring puppeteer for CI environment..."
        mkdir -p ~/.config/puppeteer
        cat > ~/.config/puppeteer/config.json << EOF
        {
          "args": ["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-gpu"]
        }
        EOF
        echo "Puppeteer config created:"
        cat ~/.config/puppeteer/config.json

    - name: Export HTML
      run: |
        echo "Exporting HTML..."
        npx resume-cli export index.html --theme danivi-style

    - name: Export PDF
      run: |
        echo "Verifying puppeteer configuration..."
        node -e "const puppeteer = require('puppeteer'); console.log('Puppeteer version:', puppeteer.defaultArgs());"
        echo "Starting PDF generation..."
        export PUPPETEER_ARGS='--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu'
        npx resume-cli export resume.pdf --theme danivi-style --format pdf
        echo "PDF generation completed"
        ls -la resume.pdf
        if [ -f resume.pdf ]; then
          echo "PDF file exists and has size: $(stat -c%s resume.pdf) bytes"
        else
          echo "PDF file was not created!"
          exit 1
        fi
      env:
        PUPPETEER_ARGS: --no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu,--disable-web-security

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4